theme: minima
title: Lou's Cottage
author: luisalopes
email: luisalopes@literatura451.com
description: > # this means to ignore newlines until "baseurl:"
  I'm... Not sure what to tell you.

# social links
twitter_username: ulliapseos # DO NOT include the @ character, or else the build will fail!
github_username:  luisalopes # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
